language: scala
script: ./build-support/sbt test
after_script:
  - ./build-support/sbt proguard
  - ./build-support/dist.sh
  - PATH=$PWD/dist/ducttape-current:$PATH ./build-support/test-regression.sh
