name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile and Package
      run: |
        sbt "set test in assembly := {}" clean assembly
        ./build-support/dist.sh

    - uses: actions/upload-artifact@master
      with:
        name: ducttape
        path: dist/ducttape-current
  
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
     
      - name: Run Unit Tests
        run: sbt test
    

  integration-tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/download-artifact@master
        with:
          name: ducttape
          path: dist/ducttape-current

      - name: Run Integration Tests
        run: ./build-support/test-regression.sh ${{ github.workspace }}/dist/ducttape-current

