name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11

    - name: Compile 
      run: sbt compile

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - name: Run Unit Tests
        run: sbt test
    

  assemble-and-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - name: Assemble and Distribute
        run: |
          sbt "set test in assembly := {}" clean assembly
          ./build-support/dist.sh

      - name: Run Integration Tests
        run: ./build-support/test-regression.sh ${{ github.workspace }}/dist/ducttape-current

