name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile and Package
      run: sbt "set test in assembly := {}" clean assembly

    - name: Run Unit Tests
      run: sbt test
    
    - name: Run Integration Tests
      run: ./build-support/test-regression.sh dist/ducttape-current

